### ISSUE TITLE
build with ImageMagick-7.1.1-16+ for windows x64

### ISSUE THREAD

**Issue by usarise** [Imagick/imagick#732]
Starting from ImageMagick version 7.1.1-16, the official x64 builds for Windows are compiled with 64-bit channel-masks.
As a result, attempting to build `imagick 3.7.0` or `imagick 3.8.0+` leads to a compilation error:

`nmake`: fatal error C1189: #error:  ImageMagick was build with a 64 channel bit mask and that requires a C++ compiler
https://github.com/ImageMagick/ImageMagick-Windows/blob/main/Projects/MagickCore/magick-baseconfig.h.in#L108

Is it possible to compile `imagick` using `Visual C++ 2019`?
Or need to compile ImageMagick with 32 channel bit mask..

**Comment by bukka** [comment]
This is already sorted in the latest version which is build with 7.1.1-46 . See https://github.com/Imagick/imagick/releases/tag/3.8.0
