### ISSUE TITLE
When will the imagick extension support php8.4? Now it will report an error

### ISSUE THREAD

**Issue by kejilion** [Imagick/imagick#698]
-----
Warning: PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20240924/imagick.so (Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20240924/imagick.so: php_strtolower: symbol not found), /usr/local/lib/php/extensions/no-debug-non-zts-20240924/imagick.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20240924/imagick.so.so: No such file or directory)) in Unknown on line 0
-----

How do I solve this problem? Thank you

**Comment by yendyr** [comment]
same problem here

**Comment by kejilion** [comment]
I'm trying to install it like this, I don't know if it works
----
docker exec php install-php-extensions Imagick/imagick@65e27f2bc0
----

**Comment by kejilion** [comment]
I'm trying to install it like this, I don't know if it works

docker exec php install-php-extensions Imagick/imagick@65e27f2bc0

**Comment by picov** [comment]
PHP 8.4.1 with ImageMagick-7.1.1-41
#pecl install imagick
....
In /tmp/pear/install/imagick/Imagick.stub.php:
Imagick::newImage(): Parameter format has null default, but is not nullable
make: *** [Makefile:191: /tmp/pear/install/imagick/Imagick_arginfo.h] Error 1
ERROR: `make INSTALL_ROOT="/tmp/pear/install/pear-build-rootti7iddt3pa35cOi0VJK/install-imagick-3.7.0" install' failed

**Comment by nephaste** [comment]
same issue with PECL install
seems better building from source... works on aarch64, but my x86_64 version has issue (weird)

**Comment by kejilion** [comment]
I have successfully installed imagick in the docker php:fpm-alpine build I used

**Comment by BowFarmer** [comment]
When I try to install it on php 8.4 with pecl, I get this:
/imagick-3.7.0/imagick.c:606:7: error: call to undeclared function 'php_strtolower'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

**Comment by BowFarmer** [comment]
I did manage to work around the 'php_strtolower' issue with php 8.4. I install imagick with pecl, and during the installation the process stops to confirm the prefix for the installation:

> Please provide the prefix of ImageMagick installation [autodetect] :

Before hitting enter I edit imagick.c which at that point in my case is in:

> /private/tmp/pear/temp/imagick/imagick.c

And I comment out line 606 with the 'php_strtolower' call which no longer seems to work in php 8.4.
`//php_strtolower(Z_STRVAL_P(retval), Z_STRLEN_P(retval));`
After that I let pecl finish the installation and it has no problems compiling and installing imagick. And I have imagick working with php 8.4 and it works fine with WordPress. Not sure what the implications are of not having that string not being converted to lowercase, but I haven't run into issues yet. I'm primarily using imagick for a WordPress development site and am testing the ramifications of using php 8.4.

**Comment by picov** [comment]
But then real question is: is this project still active ?
Latest official release is v3.7.0 released on 2022-01-11 !
Latest commit is on Mar 18, 2023 !

**Comment by picov** [comment]
@BowFarmer 
It looks like there are compatibility issues however.

**Comment by BowFarmer** [comment]
I'm not working on this project but as usarise pointed out earlier, there is a fix that is being worked on:
[https://github.com/Imagick/imagick/commit/65e27f2bc0#diff-11a53ee3341a315920a8f582c11ce3b990fd929a1fdfb742474a8a09f65ee3ebL613](url)
You can see three instances in that fix where php_strtolower has been changed to zend_str_tolower for PHP 8.4 compatibility.

**Comment by jderusse** [comment]
actually, I feel the project is not maintain anymore.
There is another issue with pho 8.3 that is fixed in master but no released (see this issue for example https://github.com/Imagick/imagick/issues/640)


I believe, someone should fork it, a d make it the new default.

**Comment by tianon** [comment]
I think this is a duplicate of #689

**Comment by GeLoLabs** [comment]
For those who want something working, here my Dockerfile:

```
# Imagick
ARG IMAGICK_VERSION=3.7.0
RUN set -eux \
    && apk add --no-cache \
      imagemagick \
      jpegoptim \
      libwebp \
      libwebp-tools \
    && apk add --no-cache --virtual .imagick-deps \
      $PHPIZE_DEPS \
      imagemagick-dev \
      libjpeg-turbo-dev \
      libpng-dev \
      libwebp-dev \
#    && pecl install imagick-"$IMAGICK_VERSION" \
#    && docker-php-ext-enable imagick \
#    && apk del .imagick-deps
    && curl -L -o /tmp/imagick.tar.gz https://github.com/Imagick/imagick/archive/tags/${IMAGICK_VERSION}.tar.gz \
    && tar --strip-components=1 -xf /tmp/imagick.tar.gz \
    && sed -i 's/php_strtolower/zend_str_tolower/g' imagick.c \
    && phpize \
    && ./configure \
    && make \
    && make install \
    && echo "extension=imagick.so" > /usr/local/etc/php/conf.d/ext-imagick.ini \
    && rm -rf /tmp/*
```

**Comment by jamesfreeman959** [comment]
Thanks for this - can confirm it works for be building on the `php:8.3.14-fpm` container image.

**Comment by BowFarmer** [comment]
Thanks.

**Comment by joeworkman** [comment]
> > I did manage to work around the 'php_strtolower' issue with php 8.4. I install imagick with pecl, and during the installation the process stops to confirm the prefix for the installation:
> > > Please provide the prefix of ImageMagick installation [autodetect] :
> > 
> > 
> > Before hitting enter I edit imagick.c which at that point in my case is in:
> > > /private/tmp/pear/temp/imagick/imagick.c
> > 
> > 
> > And I comment out line 606 with the 'php_strtolower' call which no longer seems to work in php 8.4. `//php_strtolower(Z_STRVAL_P(retval), Z_STRLEN_P(retval));` After that I let pecl finish the installation and it has no problems compiling and installing imagick. And I have imagick working with php 8.4 and it works fine with WordPress. Not sure what the implications are of not having that string not being converted to lowercase, but I haven't run into issues yet. I'm primarily using imagick for a WordPress development site and am testing the ramifications of using php 8.4.
> 
> Many thanks for sharing the workaround ... this was it but instead of commenting the line out, I replaced php_strtolower with zend_str_tolower.
> 
> Cheers!

This is exactly what I did, and it just worked for me. I am running this on an Intel Mac via homebrew.

**Comment by PaulCombal** [comment]
I'm suddenly hit with something that doesn't look like a PHP error:

```
122.1 In /tmp/pear/temp/imagick/Imagick.stub.php:
122.1 Imagick::newImage(): Parameter format has null default, but is not nullable
122.1 make: *** [Makefile:191: /tmp/pear/temp/imagick/Imagick_arginfo.h] Error 1
122.1 ERROR: `make -j8 INSTALL_ROOT="/tmp/pear/temp/pear-build-defaultuser2382nrd40alp54NOMPX/install-imagick-3.7.0" install' failed
```

The deployment somehow still succeeded so I'm at a loss

**Comment by wilianmaique** [comment]
[[3.7.0](https://pecl.php.net/package-info.php?package=imagick&version=3.7.0)](https://pecl.php.net/package/imagick/3.7.0/windows) 3.7.0 not work in php 8.4.2

**Comment by olivervogel** [comment]
I managed to get Imagick to run under PHP 8.4 and macOS with the following adjustments.

1. Install Imagemagick

```bash
brew install imagemagick
```

2. Install & Configure Imagick

```bash
git clone https://github.com/Imagick/imagick
cd imagick
phpize && ./configure
```

3. Comment out line 606 in `imagick/imagick.c` otherwise `make` will fail

4. Install Imagick

```bash
make
make install
```

5. Enable Imagick

Add `extension="imagick.so"` to `php.ini`.

**Comment by naizhao** [comment]
ServBay's build works.

**Comment by proligde** [comment]
Not sure if this info helps, but I guess it's relevant:

I have a multi arch build pipeline here using the official php 8.4 container image as build base, adding imagick-3.7.0 and it is working well on x86 but on arm64 I get the same error as @picov `Imagick::newImage(): Parameter format has null default, but is not nullable` so I assume at least that very issue might be architecture related. Or at least related to the underlying versions in the different architectures.

**Comment by tiger42** [comment]
I have exactly the same problem as @proligde in my multi arch build pipeline. I am also using the official PHP 8.4 image as base image. The amd64 (x86) version compiles fine, the arm64 version fails with the error mentioned before.

**Comment by HansVanEijsden** [comment]
I have modified my PHP build script to apply the patch automatically, from https://patch-diff.githubusercontent.com/raw/Imagick/imagick/pull/690.patch
For who finds it useful, I've attached my build script.
[php84.sh.txt](https://github.com/user-attachments/files/18304026/php84.sh.txt)

**Comment by fmonts** [comment]
The build by deb.sury.org for ubuntu (tested on 24.04) works

```bash
# add-apt-repository ppa:ondrej/php
# apt install php8.4-imagick
# php -v
PHP 8.4.2 (cli) (built: Dec 24 2024 06:05:05) (NTS)
# php --ri imagick

imagick

imagick module => enabled
imagick module version => 3.7.0
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
Imagick compiled with ImageMagick version => ImageMagick 6.9.12-98 Q16 x86_64 18038 https://legacy.imagemagick.org
Imagick using ImageMagick library version => ImageMagick 6.9.12-98 Q16 x86_64 18038 https://legacy.imagemagick.org
ImageMagick copyright => (C) 1999 ImageMagick Studio LLC
ImageMagick release date => 2024-03-31
ImageMagick number of supported formats:  => 240
```

**Comment by ProteanCode** [comment]
I did not make any tests in PHP code itself, but this compiles to PHP extension

```
RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS;
```

```
# Install Imagick from source
RUN cd /tmp && git clone --depth 1 https://github.com/Imagick/imagick.git && cd imagick \
    && sed -i 's/php_strtolower/zend_str_tolower/g' imagick.c \
    && phpize && ./configure && make && make install && ldconfig /usr/local/lib

# Add imagick extension
RUN docker-php-ext-enable imagick
```

**Comment by AlexGx** [comment]
> I managed to get Imagick to run under PHP 8.4 and macOS with the following adjustments.
works fine on MacOS 15.3.1 and php v8.4.4

**Comment by wilianmaique** [comment]
windows, php 8.4.4 not works [3.7.0](https://pecl.php.net/package/imagick/3.7.0/windows)

**Comment by leMaur** [comment]
> I managed to get Imagick to run under PHP 8.4 and macOS with the following adjustments.
> 
> 1. Install Imagemagick
> 
> brew install imagemagick
> 2. Install & Configure Imagick
> 
> git clone https://github.com/Imagick/imagick
> cd imagick
> phpize && ./configure
> 3. **Important part**: Comment out line 606 in `imagick/imagick.c` otherwise `make` will fail
> 4. Install Imagick
> 
> make
> make install
> 5. Enable Imagick
> 
> Add `extension="imagick.so"` to `php.ini`.

Instead of point 3, you can run:
```
phpize && ./configure CPPFLAGS='-Dphp_strtolower=zend_str_tolower'
```

**Comment by jtomek** [comment]
Great!... ChatGPT applied it to my docker file (keywords for people who look for this: PHP, Laravel Vapor)

```Dockerfile
# Remove or comment out the original pecl install command:
# RUN pecl install -o -f imagick && docker-php-ext-enable imagick;

# Download, patch, build, and install imagick manually:
RUN pecl download imagick \
    && tar -xzf imagick-*.tgz \
    && cd imagick-* \
    && phpize \
    && ./configure CPPFLAGS='-Dphp_strtolower=zend_str_tolower' \
    && make -j$(nproc) \
    && make install \
    && cd .. \
    && rm -rf imagick-*
    
# Enable the extension
RUN docker-php-ext-enable imagick
```

**Comment by bukka** [comment]
The changes needed were merged to develop branch and will be part of the next release. In terms of PECL release, there is already an issues open https://github.com/Imagick/imagick/issues/697

**Comment by orthello** [comment]
THANK YOU VERY MUCH!!!!!

git clone https://github.com/Imagick/imagick
cd imagick
phpize && ./configure CPPFLAGS='-Dphp_strtolower=zend_str_tolower'
add _extension=imagick.so_ to /opt/homebrew/etc/php/8.4/php.ini

**Comment by viccherubini** [comment]
If you'd prefer to use `pecl`, you can add the `CPPFLAGS` argument as an environment variable before running `pecl`:

```bash
CPPFLAGS='-Dphp_strtolower=zend_str_tolower' pecl install imagick
```

This installed the `imagick` extension version 3.7.0 on PHP 8.4.5 (from a stock Homebrew install).
