### ISSUE TITLE
Imagick 3.8.0 fails to compile with php 8.5.0RC3

### ISSUE THREAD

**Issue by sharmaharisam** [Imagick/imagick#755]
I am getting the following error when trying to install imagick's latest 3.8.0 version using php8.5.0RC3:

`Step #1 - "build": /tmp/pear/temp/imagick/imagick.c:28:10: fatal error: ext/standard/php_smart_string.h: No such file or directory
Step #1 - "build":    28 | #include "ext/standard/php_smart_string.h"
Step #1 - "build":       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Step #1 - "build": compilation terminated.
Step #1 - "build": make: *** [Makefile:226: imagick.lo] Error 1
Step #1 - "build": ERROR: `make' failed`

I see that https://github.com/Imagick/imagick/pull/741 might potentially fix this. Can anyone confirm if this is the case?

Also is there a new release version to pecl for imagick planned to address this?

**Comment by thirdwheel** [comment]
Not building with 8.5.0 under Alpine Linux

```
Configuring for:
PHP Version:             8.5
PHP Api Version:         20250925
Zend Module Api No:      20250925
Zend Extension Api No:   420250925
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking build system type... x86_64-pc-linux-musl
checking host system type... x86_64-pc-linux-musl
checking target system type... x86_64-pc-linux-musl
shtool:echo:Warning: unable to determine terminal sequence for bold mode
shtool:echo:Warning: unable to determine terminal sequence for bold mode
checking for gawk... gawk
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether cc accepts -g... yes
checking for cc option to enable C11 features... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -Wl,-rpath,... yes
checking for PHP prefix... /opt/php/8.5.0
checking for PHP includes... -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib
checking for PHP extension directory... /opt/php/8.5.0/lib/x86_64-alpine-linux-musl/20250925
checking for PHP installed headers prefix... /opt/php/8.5.0/include/php
checking if debugging is enabled... no
checking if PHP is built with thread safety (ZTS)... no

Configuring extension
checking whether to enable the imagick extension... yes, shared
checking for pkg-config... /usr/bin/pkg-config
checking ImageMagick MagickWand API configuration program... checking Testing /usr/local/bin/MagickWand-config... Doesn't exist
checking Testing /usr/bin/MagickWand-config... It exists
found in /usr/bin/MagickWand-config
checking if ImageMagick version is at least 6.5.3... found version 7.0.11-14 Q16 HDRI
checking for MagickWand.h or magick-wand.h header... user location /usr/include/ImageMagick-7/MagickWand/MagickWand.h
checking PHP version is at least 5.6.0... yes. found 8.5.0
libs
-lMagickWand-7.Q16HDRI -lMagickCore-7.Q16HDRI


checking for MagickGetVersion... yes
checking omp_pause_resource_all usability... yes
checking Which flavour of OpenMP to link... checking for omp_pause_resource_all... no
checking for __omp_pause_resource_all... no
checking for omp_pause_resource_all in -lgomp... yes
GCC flavoured OpenMP

Configuring libtool
checking for a sed that does not truncate output... /bin/sed
checking for ld used by cc... /usr/x86_64-alpine-linux-musl/bin/ld
checking if the linker (/usr/x86_64-alpine-linux-musl/bin/ld) is GNU ld... yes
checking for /usr/x86_64-alpine-linux-musl/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 98304
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool

Generating files
configure: creating build directories
configure: creating Makefile
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
/bin/sh /imagick-3.8.0/libtool --tag=CC --mode=compile cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16  -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/imagick_file.c -o imagick_file.lo  -MMD -MF imagick_file.dep -MT imagick_file.lo
/bin/sh /imagick-3.8.0/libtool --tag=CC --mode=compile cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16  -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/imagick_class.c -o imagick_class.lo  -MMD -MF imagick_class.dep -MT imagick_class.lo
/bin/sh /imagick-3.8.0/libtool --tag=CC --mode=compile cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16  -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/imagickdraw_class.c -o imagickdraw_class.lo  -MMD -MF imagickdraw_class.dep -MT imagickdraw_class.lo
/bin/sh /imagick-3.8.0/libtool --tag=CC --mode=compile cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16  -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/imagickpixel_class.c -o imagickpixel_class.lo  -MMD -MF imagickpixel_class.dep -MT imagickpixel_class.lo
/bin/sh /imagick-3.8.0/libtool --tag=CC --mode=compile cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16  -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/imagickpixeliterator_class.c -o imagickpixeliterator_class.lo  -MMD -MF imagickpixeliterator_class.dep -MT imagickpixeliterator_class.lo
/bin/sh /imagick-3.8.0/libtool --tag=CC --mode=compile cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16  -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/imagick_helpers.c -o imagick_helpers.lo  -MMD -MF imagick_helpers.dep -MT imagick_helpers.lo
/bin/sh /imagick-3.8.0/libtool --tag=CC --mode=compile cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16  -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/imagick.c -o imagick.lo  -MMD -MF imagick.dep -MT imagick.lo
/bin/sh /imagick-3.8.0/libtool --tag=CC --mode=compile cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16  -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/imagickkernel_class.c -o imagickkernel_class.lo  -MMD -MF imagickkernel_class.dep -MT imagickkernel_class.lo
/bin/sh /imagick-3.8.0/libtool --tag=CC --mode=compile cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16  -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/shim_im6_to_im7.c -o shim_im6_to_im7.lo  -MMD -MF shim_im6_to_im7.dep -MT shim_im6_to_im7.lo
mkdir .libs
mkdir .libs
mkdir: can't create directory '.libs': File exists
 cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7 -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/imagickdraw_class.c -MMD -MF imagickdraw_class.dep -MT imagickdraw_class.lo  -fPIC -DPIC -o .libs/imagickdraw_class.o
 cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7 -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/imagick_class.c -MMD -MF imagick_class.dep -MT imagick_class.lo  -fPIC -DPIC -o .libs/imagick_class.o
 cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7 -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/imagickkernel_class.c -MMD -MF imagickkernel_class.dep -MT imagickkernel_class.lo  -fPIC -DPIC -o .libs/imagickkernel_class.o
 cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7 -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/imagick.c -MMD -MF imagick.dep -MT imagick.lo  -fPIC -DPIC -o .libs/imagick.o
 cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7 -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/imagick_helpers.c -MMD -MF imagick_helpers.dep -MT imagick_helpers.lo  -fPIC -DPIC -o .libs/imagick_helpers.o
 cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7 -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/shim_im6_to_im7.c -MMD -MF shim_im6_to_im7.dep -MT shim_im6_to_im7.lo  -fPIC -DPIC -o .libs/shim_im6_to_im7.o
 cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7 -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/imagick_file.c -MMD -MF imagick_file.dep -MT imagick_file.lo  -fPIC -DPIC -o .libs/imagick_file.o
 cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7 -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/imagickpixel_class.c -MMD -MF imagickpixel_class.dep -MT imagickpixel_class.lo  -fPIC -DPIC -o .libs/imagickpixel_class.o
 cc -I. -I/imagick-3.8.0 -I/opt/php/8.5.0/include/php -I/opt/php/8.5.0/include/php/main -I/opt/php/8.5.0/include/php/TSRM -I/opt/php/8.5.0/include/php/Zend -I/opt/php/8.5.0/include/php/ext -I/opt/php/8.5.0/include/php/ext/date/lib -I/usr/include/ImageMagick-7 -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DZEND_COMPILE_DL_EXT=1 -c /imagick-3.8.0/imagickpixeliterator_class.c -MMD -MF imagickpixeliterator_class.dep -MT imagickpixeliterator_class.lo  -fPIC -DPIC -o .libs/imagickpixeliterator_class.o
/imagick-3.8.0/imagick.c:28:10: fatal error: ext/standard/php_smart_string.h: No such file or directory
   28 | #include "ext/standard/php_smart_string.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:226: imagick.lo] Error 1
make: *** Waiting for unfinished jobs....
```

Docker container used for the build: https://gist.github.com/thirdwheel/73e283fb1363c6554afae6264ae1f203

**Comment by bukka** [comment]
Imagick 3.8.1 has just been released!
